facebook/react-native-fbsdk

react-native-fbsdkcore/js-modules/FBSDKGraphRequestManager.ios.js

This is how is is done in the other files. This file throws an error in the terminal because
`NativeModules` is not available.

NativeModules call must be called on react-native

---

Sample/iOS/AppDelegate.m
Sample/iOS/Info.plist
Sample/package.json
react-native-fbsdkcore/js/FBSDKGraphRequest.ios.js
react-native-fbsdkcore/package.json
react-native-fbsdklogin/package.json
react-native-fbsdkshare/package.json

…c and iOS9.
I'm pushing this because I've seen people can't make Sample App work in iOS9. 
Do we want to keep this repo up to date with the latests versions ? 
The ugliest change it's in 
./node_modules/react-native-fbsdkcore/js/FBSDKGraphRequest.ios.js  like 112

All fixes needed to get Sample app working with react-native 0.12.0-rc and iOS9

---

react-native-fbsdkshare/iOS/RCTFBSDKAppInviteDialog.m

As discussed in https://github.com/facebook/react-native-fbsdk/issues/51

RCTFBSDKAppInviteDialog: Return NSNull in callback instead of NULL

---

react-native-fbsdkcore/package.json
react-native-fbsdklogin/package.json
react-native-fbsdkshare/package.json

Because ^ only works for all 0.13.x versions. Changing to `>=` will allow them all (note, it will also work when major is bumped, but I am not sure if that's an issue at this point, given the development lifecycle of react-native). 
Can be tested on semver.npmjs.com.
Another possible solutions:
`^v0.x` - all from 0.1.0 until 1.0.0
`0.x` - same as above

Update peerDependency requirements

---

Sample/Feed.js

This is necessary because Facebook no longer allows stream stories to
comtain images that are hosted on fbcdn.net.

Use photo link instead of image source to share a photo.

---

react-native-fbsdkshare/js/FBSDKShareDialog.ios.js

// Displays teh dialog in the main native Facebook app.
To
// Displays the dialog in the main native Facebook app.
Notice the "teh" change

Typo in FBSDKShareDialog.ios.js comment

---

README.md

Overrided onActivityResult should calls super.onActivityResult

Add missing statement in Android README

---

iOS/share/iOS/RCTFBSDKMessageDialog.m

MessageDialog.canShow(ShareContent) would always return an error because the ShareContent wasn't being set in FBSDKMessageDialog.

Fix: Set SharingContent for MessageDialog.canShow

---

README.md

[CocoaPods 1.0](https://github.com/CocoaPods/CocoaPods/releases/tag/1.0.0) has just released so we don't need to use `--pre` option.

[README] Get rid of --pre option of CocoaPods

---

js/FBLoginButton.js

The **onLoginFinished** was typed with a callback of type **LoginResultCallback** (therefore only one parameter), but **onLoginFinished** is used with two parameters at line 108.
There are two solutions to this problem.
The first is to change the call to line 108 in `this.props.onLoginFinished(eventDict)` instead of `this.props.onLoginFinished(eventDict.error, eventDict.result)`
The second is to change the typing of onLoginFinished (like in this pull request).
The first solution is breaking compatibility, the second solution isn't breaking compatibility

Fix flow issue in FBLoginButton

---

iOS/RCTFBSDK.xcodeproj/project.pbxproj

Related to: https://github.com/facebook/react-native-fbsdk/issues/181#issuecomment-221819677

 Append ${SRCROOT}/../../../ios/** to HEADER_SEARCH_PATHS to support finding local FBSDK headers installed via CocoaPods

---

ios/RCTFBSDK.xcodeproj/project.pbxproj

- Original Commit: https://github.com/facebook/react-native-fbsdk/pull/199
- It seems it was lost when the folder was renamed

ReAppend /../../../ios/** to HEADER_SEARCH_PATHS for FBSDK pods

---

js/FBLikeView.js
js/FBLoginButton.js
js/FBSendButton.js
js/FBShareButton.js

Update the ViewPropTypes to match the last revision of React Native V0.44.0
> Move View.propTypes to ViewPropTypes (53905a5) - @bvaughn 
https://github.com/facebook/react-native/releases

Update from View.propTypes to ViewPropTypes to match RNv0.44.0

---

sample/HelloFacebook/android/app/src/main/java/com/hellofacebook/MainApplication.java

The sample demo was failing in Android with this error:
```
~/react-native-fbsdk/sample/HelloFacebook/android/app/src/main/java/com/hellofacebook/MainApplication.java:59: error: getUseDeveloperSupport() in <anonymous com.hellofacebook.MainApplication$1> cannot override getUseDeveloperSupport() in ReactNativeHost
protected boolean getUseDeveloperSupport() {
^
attempting to assign weaker access privileges; was public
```
That method was changed from `protected` to `public` [here](https://github.com/facebook/react-native/pull/11329). 
This PR fixes it :)

Fix demo for Android

---

js/FBLoginButton.js

The text `Continue with Facebook` in the button was being cut off because of the width of the button container. Increasing the width of the button fixed the issue

Fix width of button

---

js/index.js

Change to use getters for modules so we do not eagerly load all modules
all the time.

Lazily require modules

---

android/src/main/java/com/facebook/reactnative/androidsdk/FBSDKPackage.java

Since of recently in master the unused createJSModules has been removed and ReactPackage's no longer contain the definition of createJSModules. There for it must be removed in order to not yield a compile error. This is breaking change.
https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8

Remove override of createJSModules

---

android/src/main/java/com/facebook/reactnative/androidsdk/FBSDKPackage.java

#345 removed the method completely. This PR is to provide backward compatibility for older react native versions.
I'm not too bothered which approach we use, remove it or keep for compatibility. Could we have a release soon to allow us to use React Native 0.47?

add createJSModules for backward compatibility

---

ios/RCTFBSDK.xcodeproj/project.pbxproj

This allows the FacebookSDK path to be configured by the main app
project instead of forcing the app to have a copy in
~Documents/FacebookSDK

Add inherited to search paths

---

ios/RCTFBSDK.xcodeproj/project.pbxproj

This pull request fixes the issue discussed here https://developers.facebook.com/bugs/111079162900447
When using react-native > 0.47 in combination with CxxBridge this project doesn't build and fails with the error 'limits' file not found.
Xiao Liang from the Facebook team proposed to open this PR here so it would be nice if you can merge it.

fixed header search path for use with CxxBridge

---

ios/RCTFBSDK/share/RCTFBSDKShareDialog.m

When a modal is opened, the `rootViewController` isn't visible, and thus the webview normally opened for authentication cannot be presented.
By looking up the top most view controller and present off of that the view is shown as expected.

make share dialog work from modals

---

ios/RCTFBSDK/share/RCTFBSDKShareDialog.m

turns out there's already a helper method to determine the topmost VC.
https://github.com/facebook/react-native/blob/e19d9dec9b3b257b5db3dc77ed8b95b93570f1e3/React/Base/RCTUtils.m#L492
Also I made a mistake in the `isBeingDismissed` part, since that should've been checked on the presented VC, not the presenting.

use helper method for topmost view controller

---

bin/ios_setup.js

The latest release includes a change that breaks the ios_setup.js script. If you follow the directions listed here in the [react native facebook sdk guide](https://developers.facebook.com/docs/react-native/configure-ios) running the command `node ios_setup.js [app id] [app name]` currently doesn't work, as the fastfall package isn't being invoked correctly according to [the docs](https://github.com/mcollina/fastfall). This fix reverts the change made in the last commit to allow the command to run successfully.

fixed how fastfall is being called

---

README.md

For people not familiar with IOS (like myself) this wasn't obvious to me until I realized I had broken other deep links in my application. Example code is based off of [this stackoverflow answer](https://stackoverflow.com/questions/38945790/appdelegate-m-for-both-fbsdk-and-linkingmanager)

Add IOS use with RCTLinkingManger to README

---

js/FBLikeView.js
js/FBLoginButton.js
js/FBSendButton.js
js/FBShareButton.js

RN no longer validates native props at runtime. This currently causes flow errors because we pass the extra parameters. This should not break older RN versions, it will just cause it to no longer validate those native props.

Update requireNativeComponent to fix flow errors

---

ios/RCTFBSDK/share/RCTFBSDKShareDialog.m

It seems like whole `canShare` should be called on UI thread.
This fixes a runtime assertion:
```
Main Thread Checker: UI API called on a background thread: -[UIApplication canOpenURL:]
ID: 28595, TID: 7945623, Thread name: (none), Queue name: com.facebook.react.FBShareDialogQueue, QoS: 0
```

Fix UI API called on a background thread

---

android/build.gradle

Starting with 0.56.0 release React Native exposes Android SDK and support library configurations via rootProject (https://github.com/facebook/react-native/commit/0a3055d98a36e49746144e883edc7e20afec4fcb). This PR try to use project settings if available..

gradle use project settings for tooling

---

android/build.gradle

avoid auto-upgrade of android facebook sdk version.
Fix for: https://stackoverflow.com/questions/52113549/app-getting-stuck-with-e-com-facebook-internal-attributionidentifiers

make facebook sdk version fixed

---

README.md

It seems like react-native install command is not working. I tried to use it but even though it says installed and linked succesfully it doesn't install the dependency and didn't installed the dependency

Fixing command to install dependency

---

android/build.gradle

Extracted RN 0.56 compat from https://github.com/facebook/react-native-fbsdk/pull/387
Could you please release a new version to NPM with all the last fixes please once you merged it
@codytwinton

React Native 0.56 compatibility (Gradle 3)

---

package.json

Based on changelog https://github.com/apache/cordova-node-xcode/blob/master/RELEASENOTES.md is version 1.0.0 stabilized version 0.9. Anyway it will be complatible with React Native 0.57.4 and up.

Increase xcode package version to minimal 1.0.0

---

ios/RCTFBSDK.xcodeproj/project.pbxproj

I'm not sure _why_ Xcode 10 stopped consistently resolving `~` to the user's home directory, but here we are.
See also: https://stackoverflow.com/questions/35590903/xcode-always-says-fbsdksharekit-fbsdksharekit-h-file-not-found
Fixes #414

Use `$(HOME)` instead of `~` for Xcode 10

---

android/build.gradle
android/src/main/java/com/facebook/reactnative/androidsdk/FBAppEventsLoggerModule.java
android/src/main/java/com/facebook/reactnative/androidsdk/Utility.java
ios/RCTFBSDK/core/RCTFBSDKAppEvents.m
js/FBAppEventsLogger.js

This adds bindings for AppEvents.setUserData which was added recently to the fb sdk. See https://developers.facebook.com/docs/app-events/advanced-matching.
Test Plan:
Tested the changes locally on iOS and android by calling the setUserData method and making sure all parameters get passed correctly.

Add bindings for AppEvents.setUserData

---

README.md

***all the steps except the pod install (Step 2)*** 
Using : 
```
"react": "16.3.1",
"react-native": "0.55.4",
"react-native-fbsdk": "^0.8.0",
```
In the step 2 of the guide it is suggested to add `pod 'FacebookSDK'` which is creating issues in the iOS  project with the `react-native-fbsdk` lib
**Example of issues :** 
During `react-native run-ios`: 
```
** BUILD FAILED **
The following build commands failed:
CompileC /Users/xxx/Documents/ReactJS/xxx/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKCoreKit.build/Objects-normal/x86_64/FBSDKAccessTokenCache.o FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/TokenCaching/FBSDKAccessTokenCache.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
```
on Xcode : 
```
Duplicate interface definition …
```

Update Readme for iOS compilation problem

---

ios/RCTFBSDK/login/RCTFBSDKLoginButtonManager.m

Related to https://github.com/facebook/react-native/pull/15894
Use RCTComponentEvent instead of the deprecated [sendInputEventWithName:body:] which will be removed when https://github.com/facebook/react-native/pull/15894 lands.
This PR should only be merged once https://github.com/facebook/react-native/pull/15894 has landed and made it to a stable release, since RCTComponentEvent does not currently exist in RN master.

Use RCTComponentEvent

---

android/build.gradle
android/src/main/java/com/facebook/reactnative/androidsdk/FBAppEventsLoggerModule.java
android/src/main/java/com/facebook/reactnative/androidsdk/FBLikeViewManager.java
android/src/main/java/com/facebook/reactnative/androidsdk/FBLoginButtonManager.java

To be compatible with RN 0.60+ we need to change from the old support lib to androidx. The only usage we have is the `Nullable` annotation so the changes are minor.
Tested the it builds in an example app with RN 0.60.0-rc.1

Migrate to Android X

---

.circleci/config.yml

Adds a super basic CI config, it runs eslint and flow. 
Next steps would be to build the example app on iOS and Android
Test Plan:
N/A

Add ci config

---

react-native-fbsdk.podspec

When published to a private podspec repo, cocoapods would download the source from master, instead of the specific version.

specify tag for source in podspec

---

ios/RCTFBSDK.xcodeproj/project.pbxproj

When using Podfile build fails and I need manually update Header Search Paths
```
pod 'FBSDKCoreKit', '~> 4.42.0'
pod 'FBSDKLoginKit', '~> 4.42.0'
pod 'FBSDKShareKit', '~> 4.42.0'
```
Fixes #501

[iOS][Fix build] Fix search paths

---

ios/RCTFBSDK.xcodeproj/project.pbxproj

See https://github.com/facebook/react-native-fbsdk/pull/417 for context.
@reidab 's pull request (#417) updated the framework search path syntax for compatibility with Xcode 10 (original issue #414). However, only the debug target's build settings were changed. This pull request modifies the release target's build settings as well. This will allow both debug and release targets to compile with Xcode 10. The screenshot below illustrates the mismatched build settings:

Modify Framework Search Path Syntax

---

ios/RCTFBSDK.xcodeproj/project.pbxproj

Xcode automatically saves the `.frameworks` files into `${REACT_NATIVE_PROJECT_DIR}/ios` directory when you **drag and drop directly to the `Frameworks/` folder and check `copy items if needed`**!
It would be convenient to reference that path for those who add the files that way. 
I personally prefer adding files that way because I do not have to keep my sdk files into `~/Documents`. 
Also your colleagues will automatically download the files from git pull(they don't need to download the sdk again and put it into `~/Downloads`) when setting up!

FacebookSDK default `framework search paths` for those who dragged and dropped and checked `copy items if needed`

---

example/ios/Podfile.lock
example/ios/RNFBSDKExample.xcodeproj/project.pbxproj
ios/RCTFBSDK/share/RCTConvert+FBSDKSharingContent.m
js/models/FBShareVideoContent.js

Previously this feature was removed from iOS and JS side of the library. It turned out that it is supported by the native FBSDK, so this PR adds it back in, the correct way.
As an extra I've fixed the iOS build issue of the example app.
The example app builds and runs.

Correct sharing a video with preview photo

---

android/src/main/java/com/facebook/reactnative/androidsdk/FBSDKPackage.java

Previously the declaration was removed but the reference to it wasn't.
Example app builds and runs.

Correct missing VERSION_TO_RELEASE symbol

---

android/build.gradle

Instead of pulling in the whole FBSDK just pull in the modules we are using.
Example app builds and runs if we consider #556 merged.

Minimize binary footprint on android

---

react-native-fbsdk.podspec

Since I've proposed to add the tag to podspec, the tags have changed to use a `v` prefix (which is a good thing IMO). But this requires a change to the podspec.

fix: tags are now prefixed with a `v`

---

README.md
android/src/main/java/com/facebook/reactnative/androidsdk/FBActivityEventListener.java
android/src/main/java/com/facebook/reactnative/androidsdk/FBGameRequestDialogModule.java
android/src/main/java/com/facebook/reactnative/androidsdk/FBLoginButtonManager.java
android/src/main/java/com/facebook/reactnative/androidsdk/FBLoginManagerModule.java
android/src/main/java/com/facebook/reactnative/androidsdk/FBMessageDialogModule.java
android/src/main/java/com/facebook/reactnative/androidsdk/FBSDKCallbackManagerBaseJavaModule.java
android/src/main/java/com/facebook/reactnative/androidsdk/FBSDKPackage.java
android/src/main/java/com/facebook/reactnative/androidsdk/FBShareDialogModule.java
example/App.js
example/android/app/src/main/java/com/rnfbsdkexample/MainActivity.java
example/android/app/src/main/java/com/rnfbsdkexample/MainApplication.java

This will simplify the package installation and fix autolinking introduced in RN 0.60
Test Plan:
Tested that the example app works, this doesn't cover all APIs but the changes are abstracted in a way that if it works for one, it should work for all.

Remove the need to pass CallbackManager to FBSDKPackage

---

package.json

Make sure Android local.properties, build/* and *.iml files are not included in npm package
Taken inspiration from https://github.com/kmagiera/react-native-reanimated/blob/master/package.json#L17
Test Plan:
Run `npm pack` and check output for `*.iml`, `*.property` and `android/build/` files.

Only include necessary Android files in package

---

ios/RCTFBSDK/core/RCTFBSDKAppEvents.m

On iOS JS null values are serialized as `NSNull`, this causes issues with the method that serializes parameters in the fbsdk. On android null values are simply ignored so this brings the same behaviour to iOS.
Test Plan:
Try calling the various methods that take a parameters object with null values and make sure they are removed.

Remove NSNull values from params dictionaries

---

android/src/main/java/com/facebook/reactnative/androidsdk/FBGameRequestDialogModule.java
android/src/main/java/com/facebook/reactnative/androidsdk/FBLoginManagerModule.java
android/src/main/java/com/facebook/reactnative/androidsdk/FBMessageDialogModule.java
android/src/main/java/com/facebook/reactnative/androidsdk/FBSDKCallbackManagerBaseJavaModule.java
android/src/main/java/com/facebook/reactnative/androidsdk/FBSDKPackage.java
android/src/main/java/com/facebook/reactnative/androidsdk/FBShareDialogModule.java

Fixes #606 
Android ShareDialog callback doesn't work.
Used one `FBActivityEventListener` instance instead of multiple instances.
Previously, we have one `FBActivityEventListener` for each module, and each one has `CallbackManager`.
However, after sharing something, the first `CallbackManager` that got called will run this [static](https://github.com/facebook/facebook-android-sdk/blob/e0080f83249559519ed226ee1c2ceffb08a17596/facebook-core/src/main/java/com/facebook/internal/CallbackManagerImpl.java#L93) [callback](https://github.com/facebook/facebook-android-sdk/blob/e2684a1e474fac878db723a29dfb90576ad7fbe8/facebook-common/src/main/java/com/facebook/share/internal/ShareInternalUtility.java#L155) (because we didn't register the callback to this manager), and make `AppCall` …

Fix sharing callback doesn't get called on Android.

---

package.json
react-native-fbsdk.podspec

Fixes #644 #646 
**Problem**
- `-canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed.` on iOS 13
- `logInWithReadPermissions returning isCancelled value always true`
**Solution**
- Update podspec dependencies version from '5.0.0' to '5.6.0'

Update podspec dependencies version

---

android/src/main/java/com/facebook/reactnative/androidsdk/FBAccessTokenModule.java
ios/RCTFBSDK/core/RCTFBSDKAccessToken.h
ios/RCTFBSDK/core/RCTFBSDKAccessToken.m
js/FBAccessToken.js

This PR adds a method which allows you to monitor the access token for changes. This enable you to have a hook which accurately represents the Facebook Access Token which will update when the user logs in or out.
It is implemented using the notifications (iOS) and tracker (Android) which the natvie Facebook SDKs provide.
**Test Plan:**
Tested on both platforms using the following hook code:
```typescript
const useFacebookToken = () => {
const [accessToken, setAccessToken] = React.useState<FBSDK.AccessToken>();
React.useEffect(() => {
FBSDK.AccessToken.getCurrentAccessToken().then(setAccessToken);
return FBSDK.AccessToken.addListener(setAccessToken);
}, []);
return accessToken;
};
```

Add method to listen for changes to the access token

---

README.md

Update Readme with React Native version table to explain versions of react-native-fbsdk greater than 1.0rc0 require React Native 0.60 or greater.
Test Plan: Non applicable.

Update README.md with React Native version compatibility explanation.

---

android/build.gradle

As noted on the title, added `safeExtGet` function seen in many other RN library projects so that we can remove some redundant version check code.
Test Plan:

Chore/introduce safeExtGet to simplify root project property access

---

react-native-fbsdk.podspec

Update facebook sdks to latest version `5.8.0` which is already used on android
Test Plan:
We use this change in our app:

update facebook sdks to 5.8.0 for ios

---

example/ios/Podfile.lock
example/ios/RNFBSDKExample.xcodeproj/project.pbxproj

This updates `Podfile.lock` which fixes the example app on iOS.
Fixes #655
<p align="center">
</p>

Update and fix Podfile.lock

---

react-native-fbsdk.podspec

This PR aims to keep Facebook SDK at 5.8.0. Currently if we try to `pod install` or `pod update` the project, it will automatically install latest version of FBSDKCoreKit (5.10.0), which leads to issue #667 . By keeping it at exactly 5.8.0, that issue is solved.
Test Plan:
Just use the updated `react-native-fbsdk.podspec` file, and don't forget to `pod update`. Tested on RN 0.61.4 and 0.60.1.

Keep Facebook SDK at 5.8

---

android/src/main/java/com/facebook/reactnative/androidsdk/FBAccessTokenModule.java

The access token change event is broadcasted from AccessTokenTracker
during app start, even before the react-native has fully initialized.
This results in a RuntimeException while trying to retrieve the
JSModule from context. This is just a safe escape hatch to avoid app
crashing. A more robust solution might be deferring the change event
after the react-native initializes.
Fixes #726

Avoid app crashing on access token change

---

react-native-fbsdk.podspec

The native FBSSDK has support for tvOS but in the podspec for this repo it was not added. We use the SDK in out Apps and needed this support. So I added it an hope that it can get merged into the library.

Update podspec for tvOS

---

android/build.gradle

Android Studio 3.6.3 is now available:
https://androidstudio.googleblog.com/2020/04/android-studio-363-available.html

Update Android Gradle plugin to 3.6.3

---

package.json

I'm using `react-native: 0.59.10` and when I install I see this `warning: react-native-fbsdk@1.1.2 has incorrect peer dependency "react-native@>=0.60.0"`
Test Plan:
When install the package this warning should not appear

Fix react native peer dependencies

---

android/src/main/java/com/facebook/reactnative/androidsdk/FBAppEventsLoggerModule.java
ios/RCTFBSDK/core/RCTFBSDKAppEvents.m
src/FBAppEventsLogger.js

Fixes #599 
- Added access to anonymousID, attributionID and advertiserID from native sdks.
Test Plan:
Integrate the sdk to any project and try to get this values:
```js
import {AppEventsLogger} from 'react-native-fbsdk';
...
AppEventsLogger.getAnonymousID()
.then(anonymousID => {
console.log('anonymousID fbsdk', anonymousID);
})
.catch(e => {
console.error(e);
});
AppEventsLogger.getAdvertiserID()
.then(advertiserID => {
console.log('advertiserID fbsdk', advertiserID);
})
.catch(e => {
console.error(e);
});
AppEventsLogger.getAttributionID()
.then(attributionID => {
console.log('attributionID fbsdk', attributionID);
})
.catch(e => {
console.error(e);
});
...
```
Note that `attributionID` will be empty on emulators.

Add getters for anonymousID, attributionID and advertiserID

---

android/build.gradle
android/src/main/java/com/facebook/reactnative/androidsdk/FBSDKPackage.java
android/src/main/java/com/facebook/reactnative/androidsdk/FBSettingsModule.java
example/ios/Podfile.lock
ios/RCTFBSDK/core/RCTFBSDKSettings.h
ios/RCTFBSDK/core/RCTFBSDKSettings.m
react-native-fbsdk.podspec
src/FBSettings.js
src/index.js

What is this commit about:
* Updated FB iOS SDK to v8.0 which has the necessary updates for iOS 14
* Updated FB Android SDK to v7.1.0+ which the API for CCPA compliance
* Provided `setDataProcessingOptions` API for CCPA compliance for both iOS and Android
* Provided access to `getAdvertiserTrackingEnabled` and `setAdvertiserTrackingEnabled` which are necessary for iOS 14
Test Plan:
1. Create sample project
2. Integrate the SDK
3. Add below code to verify the new API works
```
<Button
title="ATE"
onPress={() =>
Settings.setAdvertiserTrackingEnabled(true).then( (result) => {
console.log("is success: " + result);
Settings.getAdvertiserTrackingEnabled().then((result) => {
console.log("ATE: " + result);
Settings.setAdvertiserTrackingEnabled(false).then( (result) => {
console.log("is success: " …
```

Expose API for CCPA compliance and iOS 14 ATE

---

android/build.gradle
android/src/main/java/com/facebook/reactnative/androidsdk/FBAppLinkModule.java
android/src/main/java/com/facebook/reactnative/androidsdk/FBSDKPackage.java
ios/RCTFBSDK.xcodeproj/project.pbxproj
ios/RCTFBSDK/core/RCTFBSDKAppLink.h
ios/RCTFBSDK/core/RCTFBSDKAppLink.m
src/FBAppLink.js
src/index.js

Using facebook deferred app link in react-native project was a bit painful, because it isn't included in react-native-fbsdk.
Simply warp the `fetchDeferredAppLink` function from native.
1. Use `fetchDeferredAppLink` from [FBSDKAppLinkUtility](https://developers.facebook.com/docs/reference/ios/current/class/FBSDKAppLinkUtility)
2. Convert app link url from `NSURL` to `NSString` if app link is found and pass it to JS using `RCTPromiseResolveBlock`.
3. Resolve `null` if app link is not found. 
1. Use `fetchDeferredAppLinkData` from [AppLinkData](https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/applinks/applinkdata.html)
2. If `appLinkData` is found, convert its `Uri` to `String` and pass it to JS using `com.facebook.react.bridge.Promise`. 
3. Resolve …

Implement fetch deferred app link
